### ISSUE TITLE
tldextract dependency version 3.6.0 has been yanked on pypi

### ISSUE THREAD

**Issue by mlodic** [typosquatter/ail-typo-squatting#14]
Hello guys, :) 

thank you for your project :)

While installing your library with the latest version (2.7.2) we had this error:

```
ERROR: No matching distribution found for tldextract<4.0.0,>=3.6.0
```

We noticed that tldextract 3.6.0 has been yanked in [pypi](https://pypi.org/project/tldextract/3.6.0/). Could you please update the requirements of the project?

Thank you :)

**Comment by DavidCruciani** [comment]
Hello @mlodic,
Thanks for the report, it's up-to date now. 1c0499a12818789a73145885776cf98248e15265
