### ISSUE TITLE
Poetry install broken

### ISSUE THREAD

**Issue by iam-py-test** [typosquatter/ail-typo-squatting#16]
get-poetry.py seems deprecated and `https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py` returns a 404.
The website<sup>[[1]](https://python-poetry.org/docs/#installing-with-the-official-installer)</sup> recommends using `curl -sSL https://install.python-poetry.org | python3 -` instead (though in my opinion, this is pretty much equivalent to `curl | bash` which is bad practice).
Thanks

**Comment by adulau** [comment]
Thanks I updated the documentation.  The self-installation of Poetry is kind of chicken-egg issue. As long poetry distribution doesn't get compromised, we are fine ;-)
