### ISSUE TITLE
Link to website from this README

### ISSUE THREAD

**Issue by corneliusroemer** [typosquatter/ail-typo-squatting#19]
I love the tool, it's useful! But using it right now requires some knowledge of Python and even then some somewhat cumbersome steps (cloning etc.)

Would be great if there was a simple website where one can input a domain name and gets a list of possible typos.

It _might_ be possible to avoid having to setup a server/backend (via wasm, pyodide, rust python or the like) - that would simplify deploy - but with low usage this should be dirt-cheap to free even if you were to go for a simple server.

**Comment by adulau** [comment]
There is ;-) 

The online public version is available here https://typosquatting-finder.circl.lu/ and the source code is available there https://github.com/typosquatter/ail-typo-website

**Comment by corneliusroemer** [comment]
Thanks, I see! Maybe advertise is more prominently in the README - I didn't find it and had no reason to believe something existed from the README alone.

This link here goes to docs that again don't say anything about a website (I would have expected that this link goes to a deployment if one exists).

<img width="481" alt="Brave Browser 2024-09-08 12 52 25" src="https://github.com/user-attachments/assets/582ea9dd-bf0c-4e58-87d7-c8f3cc702ec0">

**Comment by adulau** [comment]
Good point. It's now fixed.
