### ISSUE TITLE
Add Non-Adjacent Character Swap algorithm

### ISSUE THREAD

**Issue by Bearloggs** [typosquatter/ail-typo-squatting#2]
It would be great if a non-adjacent character swap algorithm would be added to search related domain name.  
For instance for the domain abcd.com, you could test for adcb.com, cbad.com, ... Thanks

**Comment by DavidCruciani** [comment]
@Gatochoco
Thanks a lot for your feedback, the new algo is implemented, you can see changes here https://github.com/ail-project/ail-typo-squatting/commit/57158fd1cf965cf2df5d48c1cce3fdecdcfda4ad.


Let us know if you find an other algo that can be missing.
