### ISSUE TITLE
TLD-Swap add .uk 

### ISSUE THREAD

**Issue by TiiTcHY** [typosquatter/ail-typo-squatting#5]
Would it be possible to add .uk to the TLD Swap algorithm

**Comment by DavidCruciani** [comment]
Hi @TiiTcHY,

Are you talking about `wrongTld` ? If it is, then `.uk` is already in the algorithm.

In case of domain like `circl.co.uk`, there will be variations like `circl.co.lu` and `circl.lu`.
One by removing `uk` and an other by removing `co.uk`.

Is it what you are asking ?

**Comment by TiiTcHY** [comment]
Hi @DavidCruciani 

Yes. However, if you did `circl.com` it would do different variations like `circl.sx` and `circl.lu` but not `circl.uk` or `circl.co.uk`.

**Comment by DavidCruciani** [comment]
I did a test minutes ago with `circl.com` and it give me `circl.uk`. It's normal that `co.uk` is not added in this algorithm cause it's using [this](https://data.iana.org/TLD/tlds-alpha-by-domain.txt) TLD list.
Are you sure you do not see `circl.uk` ?
This is the command I typed in poetry shell: `python typo.py -dn circl.com -wt -o -`

**Comment by TiiTcHY** [comment]
Hi @DavidCruciani it would appear that i missed it then. However, would it be possible to get the .co.uk added?

**Comment by DavidCruciani** [comment]
Hello @TiiTcHY,

Find changes [here](https://github.com/ail-project/ail-typo-squatting/commit/fe54994d27735d62ff96fd92b4e5351bd69d318c).

Compose TLD will be added only when the current tld match:
`circl.lu` -> `circl.blogspot.lu`
`circl.uk` -> `circl.ac.uk`, `circl.co.uk`...

If each sld is added the list for the wrongTld algorithm will be very long.

Regards.

**Comment by TiiTcHY** [comment]
Hi @DavidCruciani  Thank you.
